print("**********************************")
print("*        IDENTIFICACION          *")
print("**********************************")
print("Nombre Completo: Luis Bustos Marin")
print("RUT: 17.052.125-0")
